name: "test-variable"
description: "test variable"

# 👈 这里完全不需要定义 inputs 和 env 映射！

runs:
  using: "composite"
  steps:
    - name: Run External Bash Script
      shell: bash
      run: bash ./scripts/test-variable.sh  # 👈 直接调脚本