name: Unit Test

on:
  workflow_call:  # 👈 允许被其他 workflow 调用

jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Run Unit Tests
        run: |
          python --version