name: Feature PR to main

on:
  pull_request:
    branches:
      - main
    types: [opened, synchronize]

jobs:
  pre-commit:
    if: startsWith(github.head_ref, 'feature/')
    uses: ./.github/workflows/_pre-commit.yml
