name: Push to main

on:
  push:
    branches: [ main ]

jobs:
  pre-commit:
    name: "code-check: Pre-Commit"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository  # 👈 必须有这一步！先把代码拉到虚拟机里
        uses: actions/checkout@v4

      - name: Run Pre-Commit Action
        uses: ./.github/actions/pre-commit # 👈 这样才能找到 .github/actions/pre-commit/action.yml

  version-check:
    name: "code-check: Version Check"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository  # 👈 同样，这一步不能少
        uses: actions/checkout@v4

      - name: Run Version Check Action
        uses: ./.github/actions/version-check