name: test workflow

on:
  workflow_dispatch:

jobs:
  job1:
    runs-on: ubuntu-22.04
    steps:
      - run: echo "job1"
  job2:
    runs-on: ubuntu-22.04
    steps:
      - run: echo "job2"  
  job3:
    runs-on: ubuntu-22.04
    steps:
      - run: echo "job3"
    needs: [job1, job2]
  job4:
    runs-on: ubuntu-22.04
    steps:
      - run: echo "job3"
    needs: [job3]
    
