name: Build inside container
on:
    push:
        branches: [ main ]
    
jobs:
    container-build-job:
        runs-on: ubuntu-latest
        container:
            image: mcr.microsoft.com/dotnet/sdk:6.0
        steps:
            - uses: actions/checkout@v5
            - name: tets
              run: ls -al
