name: test-workflow-command

on:
  push:
    branches: [ main ]
jobs:
  job1:
    runs-on: ubuntu-latest
    name: job1
    env:
      ACTIONS_STEP_DEBUG: true #add
    steps:
      - name: Print warning annotation
        run: echo "::warning file=test.py,line=1,col=5,endColumn=7::Missing semicolon"

      - name: Print error annotation
        run: echo "::error file=test.py,line=1,col=5,endColumn=7::Error in test.py"        
        
      - run: |
          echo "::group::编译核心业务代码"
          echo "test"
          echo "::endgroup::"
        
      - run: |
          echo "::debug:: debug info"