name: test workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  first_job:
    runs-on: ubuntu-22.04
    steps:
      - run: echo 'test'

      - name: checkout
        uses: uses: actions/checkout@v7.0.0
      - name: list files
        run: |
          echo "The repo ${{github.repository}} contains the following files:"
          tree
      
  
    
 
