name: test-variable

on:
  push:
    branches: [ main ]

env:
    USER_NAME: "Alice"    # 👈 这个变量会自动注入到整个 Job 的运行环境中！

# 1. 在 Job 级别（或全局）直接声明 env
jobs:
  test-variable:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: 调用 Local Action（不需要写 with！）
        uses: ./.github/actions/test-variable